kind: pipeline
# type: docker
name: default

platform:
  # os: linux
  arch: arm64

steps:
  - name: setup
    image: python:3.8
    commands:
      - pip install -r requirements.txt || true 

  - name: run
    image: python:3.8
    commands:
      - pip install -r requirements.txt
      - python main.py

  - name: test
    image: python:3.8
    commands:
      - pip install pytest
      - pytest

# kind: pipeline
# type: docker
# name: simple-pipeline

# steps:
#   - name: greet
#     image: alpine
#     commands:
#       - echo "Hello, Drone CI!"

#   - name: environment-check
#     image: alpine
#     commands:
#       - echo "Listing environment variables:"
#       - env

#   - name: display-date
#     image: alpine
#     commands:
#       - echo "The current date and time is:"
#       - date
