kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: python:3.8
    commands:
      - pip install -r requirements.txt || true 

  - name: run
    image: python:3.8
    commands:
      - python main.py

  - name: test
    image: python:3.8
    commands:
      - pip install pytest
      - pytest
