version: '3'

services:
  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
      - 8000:80
    volumes:
      - ./drone_data:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=localhost
      - DRONE_SERVER_PROTO=http
      - DRONE_USER_CREATE=username:moabukar,admin:true
      - DOCKER_UI_USERNAME=root
      - DOCKER_UI_PASSWORD=root

  drone-agent:
    image: drone/drone-runner-docker:latest
    container_name: drone-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=agent
