version: '3.8'

services:
  drone:
    image: drone/drone:2
    container_name: drone
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=4cff-86-171-212-33.ngrok-free.app
      - DRONE_SERVER_PROTO=https
      - DRONE_UI_USERNAME=${DRONE_UI_USERNAME}
      - DRONE_UI_PASSWORD=${DRONE_UI_PASSWORD}

    ports:
      - "8080:80"
    networks:
      - drone-net
    restart: always

  runner:
    image: drone/drone-runner-docker:1
    container_name: runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_NAME=runner-demo
    ports:
      - "3000:3000"
    networks:
      - drone-net
    restart: always

networks:
  drone-net:

