version: '3.8'

services:
  drone:
    image: drone/drone:2
    container_name: drone
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=4cff-86-171-212-33.ngrok-free.app
      - DRONE_SERVER_PROTO=https
    ports:
      - "8080:80"
    networks:
      - drone-net
    restart: always

networks:
  drone-net:
